# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'part2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mothongdiep(object):
    def setupUi(self, Mothongdiep):
        Mothongdiep.setObjectName("Mothongdiep")
        Mothongdiep.resize(1142, 767)
        self.widget = QtWidgets.QWidget(Mothongdiep)
        self.widget.setGeometry(QtCore.QRect(230, 170, 611, 344))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.PBCo = QtWidgets.QPushButton(self.widget)
        self.PBCo.setGeometry(QtCore.QRect(160, 250, 101, 41))
        self.PBCo.setStyleSheet("QPushButton{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 255)\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 255, 0);\n"
"    border: 3px solid rgb(0, 255, 0);\n"
" }")
        self.PBCo.setObjectName("PBCo")
        self.PBKhong = QtWidgets.QPushButton(self.widget)
        self.PBKhong.setGeometry(QtCore.QRect(340, 250, 101, 41))
        self.PBKhong.setStyleSheet("QPushButton{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 255, 0);\n"
"    border: 3px solid rgb(0, 255, 0);\n"
" }")
        self.PBKhong.setObjectName("PBKhong")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 551, 61))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(90, 140, 431, 61))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 611, 344))
        self.label.setStyleSheet("border-radius: 50px;\n"
"background-color: rgba(0, 0, 0, 200);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.PBCo.raise_()
        self.PBKhong.raise_()
        self.label_2.raise_()
        self.label_3.raise_()

        self.retranslateUi(Mothongdiep)
        QtCore.QMetaObject.connectSlotsByName(Mothongdiep)

    def retranslateUi(self, Mothongdiep):
        _translate = QtCore.QCoreApplication.translate
        Mothongdiep.setWindowTitle(_translate("Mothongdiep", "Form"))
        self.PBCo.setText(_translate("Mothongdiep", "Có"))
        self.PBKhong.setText(_translate("Mothongdiep", "Không"))
        self.label_2.setText(_translate("Mothongdiep", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ff0000;\">Bạn vừa nhận được một thông điệp.</span></p></body></html>"))
        self.label_3.setText(_translate("Mothongdiep", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; font-style:italic; color:#ff0000;\">Bạn có muốn mở nó không?</span></p></body></html>"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mothongdiep = QtWidgets.QWidget()
    ui = Ui_Mothongdiep()
    ui.setupUi(Mothongdiep)
    Mothongdiep.show()
    sys.exit(app.exec_())
