# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'part3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bennhan(object):
    def setupUi(self, Bennhan):
        Bennhan.setObjectName("Bennhan")
        Bennhan.resize(1092, 693)
        self.widget = QtWidgets.QWidget(Bennhan)
        self.widget.setGeometry(QtCore.QRect(50, 60, 1000, 559))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-image: url(:/newPrefix/bennhan.jpg);\n"
"border-radius: 50px;\n"
"}")
        self.widget.setObjectName("widget")
        self.TEChukynhanduoc = QtWidgets.QTextEdit(self.widget)
        self.TEChukynhanduoc.setGeometry(QtCore.QRect(50, 360, 391, 111))
        self.TEChukynhanduoc.setStyleSheet("QTextEdit{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255,255, 255,50);\n"
"}\n"
"QTextEdit:focus{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}")
        self.TEChukynhanduoc.setObjectName("TEChukynhanduoc")
        self.LChukynhanduoc = QtWidgets.QLabel(self.widget)
        self.LChukynhanduoc.setGeometry(QtCore.QRect(60, 320, 351, 31))
        self.LChukynhanduoc.setObjectName("LChukynhanduoc")
        self.LMabamSHA1 = QtWidgets.QLabel(self.widget)
        self.LMabamSHA1.setGeometry(QtCore.QRect(580, 140, 251, 31))
        self.LMabamSHA1.setObjectName("LMabamSHA1")
        self.PBXacminh = QtWidgets.QPushButton(self.widget)
        self.PBXacminh.setGeometry(QtCore.QRect(570, 490, 141, 41))
        self.PBXacminh.setStyleSheet("QPushButton{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 0, 255);\n"
"    border: 3px solid rgb(0, 0, 255);\n"
" }")
        self.PBXacminh.setObjectName("PBXacminh")
        self.LThamdinhchukysoRSA = QtWidgets.QLabel(self.widget)
        self.LThamdinhchukysoRSA.setGeometry(QtCore.QRect(110, 40, 781, 71))
        self.LThamdinhchukysoRSA.setObjectName("LThamdinhchukysoRSA")
        self.LThongdiepnhanduoc = QtWidgets.QLabel(self.widget)
        self.LThongdiepnhanduoc.setGeometry(QtCore.QRect(60, 140, 361, 31))
        self.LThongdiepnhanduoc.setObjectName("LThongdiepnhanduoc")
        self.TEGiaimachuky = QtWidgets.QTextEdit(self.widget)
        self.TEGiaimachuky.setGeometry(QtCore.QRect(570, 360, 391, 111))
        self.TEGiaimachuky.setStyleSheet("QTextEdit{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255,255, 255,50);\n"
"}\n"
"QTextEdit:focus{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}")
        self.TEGiaimachuky.setObjectName("TEGiaimachuky")
        self.TEThongdiepnhanduoc = QtWidgets.QTextEdit(self.widget)
        self.TEThongdiepnhanduoc.setGeometry(QtCore.QRect(50, 180, 391, 131))
        self.TEThongdiepnhanduoc.setStyleSheet("QTextEdit{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255,255, 255,50);\n"
"}\n"
"QTextEdit:focus{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}")
        self.TEThongdiepnhanduoc.setObjectName("TEThongdiepnhanduoc")
        self.TEMabamSHA1 = QtWidgets.QTextEdit(self.widget)
        self.TEMabamSHA1.setGeometry(QtCore.QRect(570, 180, 391, 131))
        self.TEMabamSHA1.setStyleSheet("QTextEdit{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255,255, 255,50);\n"
"}\n"
"QTextEdit:focus{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}")
        self.TEMabamSHA1.setObjectName("TEMabamSHA1")
        self.LGiaimachuky = QtWidgets.QLabel(self.widget)
        self.LGiaimachuky.setGeometry(QtCore.QRect(580, 320, 251, 31))
        self.LGiaimachuky.setObjectName("LGiaimachuky")
        self.PBThoat = QtWidgets.QPushButton(self.widget)
        self.PBThoat.setGeometry(QtCore.QRect(870, 490, 91, 41))
        self.PBThoat.setStyleSheet("QPushButton{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 0, 255);\n"
"    border: 3px solid rgb(0, 0, 255);\n"
" }")
        self.PBThoat.setObjectName("PBThoat")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1000, 559))
        self.label.setStyleSheet("border-radius: 50px;\n"
"background-color: rgba(0, 0, 0, 100);")
        self.label.setObjectName("label")
        self.PBQuaylai = QtWidgets.QPushButton(self.widget)
        self.PBQuaylai.setGeometry(QtCore.QRect(730, 490, 121, 41))
        self.PBQuaylai.setStyleSheet("QPushButton{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 0, 255);\n"
"    border: 3px solid rgb(0, 0, 255);\n"
" }")
        self.PBQuaylai.setObjectName("PBQuaylai")
        self.label.raise_()
        self.TEChukynhanduoc.raise_()
        self.LChukynhanduoc.raise_()
        self.LMabamSHA1.raise_()
        self.PBXacminh.raise_()
        self.LThamdinhchukysoRSA.raise_()
        self.LThongdiepnhanduoc.raise_()
        self.TEGiaimachuky.raise_()
        self.TEThongdiepnhanduoc.raise_()
        self.TEMabamSHA1.raise_()
        self.LGiaimachuky.raise_()
        self.PBThoat.raise_()
        self.PBQuaylai.raise_()

        self.retranslateUi(Bennhan)
        QtCore.QMetaObject.connectSlotsByName(Bennhan)

    def retranslateUi(self, Bennhan):
        _translate = QtCore.QCoreApplication.translate
        Bennhan.setWindowTitle(_translate("Bennhan", "Form"))
        self.LChukynhanduoc.setText(_translate("Bennhan", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00ff00;\">Chữ ký nhận được:</span></p></body></html>"))
        self.LMabamSHA1.setText(_translate("Bennhan", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00ff00;\">Mã băm (SHA1):</span></p></body></html>"))
        self.PBXacminh.setText(_translate("Bennhan", "Xác minh"))
        self.LThamdinhchukysoRSA.setText(_translate("Bennhan", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; font-style:italic; color:#ff0000;\">Thẩm định chữ ký số RSA</span></p></body></html>"))
        self.LThongdiepnhanduoc.setText(_translate("Bennhan", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00ff00;\">Thông điệp nhận được:</span></p></body></html>"))
        self.LGiaimachuky.setText(_translate("Bennhan", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00ff00;\">Giải mã chữ ký:</span></p></body></html>"))
        self.PBThoat.setText(_translate("Bennhan", "Thoát"))
        self.label.setText(_translate("Bennhan", "TextLabel"))
        self.PBQuaylai.setText(_translate("Bennhan", "Quay lại"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bennhan = QtWidgets.QWidget()
    ui = Ui_Bennhan()
    ui.setupUi(Bennhan)
    Bennhan.show()
    sys.exit(app.exec_())
