# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'part4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1030, 750)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(210, 180, 611, 344))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.PBDong = QtWidgets.QPushButton(self.widget)
        self.PBDong.setGeometry(QtCore.QRect(240, 250, 131, 41))
        self.PBDong.setStyleSheet("QPushButton{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 255, 0);\n"
"    border: 3px solid rgb(0, 255, 0);\n"
" }")
        self.PBDong.setObjectName("PBDong")
        self.LLammo = QtWidgets.QLabel(self.widget)
        self.LLammo.setGeometry(QtCore.QRect(0, 0, 611, 344))
        self.LLammo.setStyleSheet("border-radius: 50px;\n"
"background-color: rgba(0, 0, 0, 200);")
        self.LLammo.setText("")
        self.LLammo.setObjectName("LLammo")
        self.TBThongbao = QtWidgets.QTextBrowser(self.widget)
        self.TBThongbao.setGeometry(QtCore.QRect(60, 70, 501, 151))
        self.TBThongbao.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(255, 0, 0);\n"
"border: none;\n"
"font: 75 28pt \"MS Shell Dlg 2\";")
        self.TBThongbao.setObjectName("TBThongbao")
        self.LLammo.raise_()
        self.PBDong.raise_()
        self.TBThongbao.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.PBDong.setText(_translate("Form", "Đóng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
