# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'part1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bengui(object):
    def setupUi(self, Bengui):
        Bengui.setObjectName("Bengui")
        Bengui.resize(1080, 675)
        Bengui.setStyleSheet("#Bengui{\n"
"background-image: url(:/newPrefix/AdobeStock_141951442-1080x675.jpeg);\n"
"}")
        self.widget = QtWidgets.QWidget(Bengui)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1080, 675))
        self.widget.setStyleSheet("QWidget#widget{\n"
"border-radius: 50px;\n"
"background-image: url(:/newPrefix/AdobeStock_141951442-1080x675.jpeg);\n"
"}")
        self.widget.setObjectName("widget")
        self.LKhoabimat = QtWidgets.QLabel(self.widget)
        self.LKhoabimat.setGeometry(QtCore.QRect(40, 570, 181, 51))
        self.LKhoabimat.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.LKhoabimat.setObjectName("LKhoabimat")
        self.PBTinh = QtWidgets.QPushButton(self.widget)
        self.PBTinh.setGeometry(QtCore.QRect(180, 100, 101, 41))
        self.PBTinh.setStyleSheet("QPushButton{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 0, 255);\n"
"    border: 3px solid rgb(0, 0, 255);\n"
" }")
        self.PBTinh.setObjectName("PBTinh")
        self.TEThongdiepdulieu = QtWidgets.QTextEdit(self.widget)
        self.TEThongdiepdulieu.setGeometry(QtCore.QRect(520, 140, 531, 181))
        self.TEThongdiepdulieu.setStyleSheet("QTextEdit{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255,255, 255,50);\n"
"}\n"
"QTextEdit:focus{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}")
        self.TEThongdiepdulieu.setObjectName("TEThongdiepdulieu")
        self.LTaochukysoRSA = QtWidgets.QLabel(self.widget)
        self.LTaochukysoRSA.setGeometry(QtCore.QRect(520, 10, 521, 71))
        self.LTaochukysoRSA.setStyleSheet("QWidget#wiget{\n"
"background-image:url(:/newPrefix/AdobeStock_141951442-1080x675.jpeg);\n"
"}")
        self.LTaochukysoRSA.setObjectName("LTaochukysoRSA")
        self.Lp = QtWidgets.QLabel(self.widget)
        self.Lp.setGeometry(QtCore.QRect(20, 178, 51, 31))
        self.Lp.setObjectName("Lp")
        self.LEPn = QtWidgets.QLineEdit(self.widget)
        self.LEPn.setGeometry(QtCore.QRect(270, 280, 131, 31))
        self.LEPn.setStyleSheet("QLineEdit{\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgb(0, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"border: none;\n"
"border-bottom: 2px solid rgb(0, 0, 255);\n"
"}")
        self.LEPn.setObjectName("LEPn")
        self.Lq = QtWidgets.QLabel(self.widget)
        self.Lq.setGeometry(QtCore.QRect(20, 268, 55, 31))
        self.Lq.setObjectName("Lq")
        self.LThongdiepdulieu = QtWidgets.QLabel(self.widget)
        self.LThongdiepdulieu.setGeometry(QtCore.QRect(520, 90, 241, 41))
        self.LThongdiepdulieu.setObjectName("LThongdiepdulieu")
        self.Le = QtWidgets.QLabel(self.widget)
        self.Le.setGeometry(QtCore.QRect(20, 368, 55, 31))
        self.Le.setStyleSheet("color: rgb(0, 170, 0)")
        self.Le.setObjectName("Le")
        self.LPn = QtWidgets.QLabel(self.widget)
        self.LPn.setGeometry(QtCore.QRect(200, 278, 71, 31))
        self.LPn.setObjectName("LPn")
        self.LEn = QtWidgets.QLineEdit(self.widget)
        self.LEn.setGeometry(QtCore.QRect(270, 180, 131, 31))
        self.LEn.setStyleSheet("QLineEdit{\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgb(0, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"border: none;\n"
"border-bottom: 2px solid rgb(0, 0, 255);\n"
"}")
        self.LEn.setText("")
        self.LEn.setObjectName("LEn")
        self.LEd = QtWidgets.QLineEdit(self.widget)
        self.LEd.setGeometry(QtCore.QRect(270, 370, 131, 31))
        self.LEd.setStyleSheet("QLineEdit{\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgb(0, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"border: none;\n"
"border-bottom: 2px solid rgb(0, 0, 255);\n"
"}")
        self.LEd.setObjectName("LEd")
        self.LKhoacongkhai = QtWidgets.QLabel(self.widget)
        self.LKhoacongkhai.setGeometry(QtCore.QRect(40, 470, 231, 51))
        self.LKhoacongkhai.setStyleSheet("color: rgb(0, 255, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.LKhoacongkhai.setObjectName("LKhoacongkhai")
        self.PBGui = QtWidgets.QPushButton(self.widget)
        self.PBGui.setEnabled(True)
        self.PBGui.setGeometry(QtCore.QRect(791, 610, 141, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.PBGui.setFont(font)
        self.PBGui.setStyleSheet("QPushButton{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 0, 255);\n"
"    border: 3px solid rgb(0, 0, 255);\n"
" }")
        self.PBGui.setObjectName("PBGui")
        self.PBXoachuky = QtWidgets.QPushButton(self.widget)
        self.PBXoachuky.setGeometry(QtCore.QRect(950, 330, 101, 41))
        self.PBXoachuky.setStyleSheet("QPushButton{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 0, 255);\n"
"    border: 3px solid rgb(0, 0, 255);\n"
" }")
        self.PBXoachuky.setObjectName("PBXoachuky")
        self.Ln = QtWidgets.QLabel(self.widget)
        self.Ln.setGeometry(QtCore.QRect(220, 178, 71, 31))
        self.Ln.setObjectName("Ln")
        self.LSinhkhoa = QtWidgets.QLabel(self.widget)
        self.LSinhkhoa.setGeometry(QtCore.QRect(30, 10, 371, 71))
        self.LSinhkhoa.setStyleSheet("")
        self.LSinhkhoa.setObjectName("LSinhkhoa")
        self.LEe = QtWidgets.QLineEdit(self.widget)
        self.LEe.setGeometry(QtCore.QRect(60, 370, 131, 31))
        self.LEe.setStyleSheet("QLineEdit{\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgb(0, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"border: none;\n"
"border-bottom: 2px solid rgb(0, 0, 255);\n"
"}")
        self.LEe.setObjectName("LEe")
        self.TEChukyso = QtWidgets.QTextEdit(self.widget)
        self.TEChukyso.setGeometry(QtCore.QRect(520, 500, 531, 101))
        self.TEChukyso.setStyleSheet("QTextEdit{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255,255, 255,50);\n"
"}\n"
"QTextEdit:focus{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}")
        self.TEChukyso.setObjectName("TEChukyso")
        self.LChukyso = QtWidgets.QLabel(self.widget)
        self.LChukyso.setGeometry(QtCore.QRect(520, 450, 151, 41))
        self.LChukyso.setObjectName("LChukyso")
        self.LEp = QtWidgets.QLineEdit(self.widget)
        self.LEp.setGeometry(QtCore.QRect(60, 180, 131, 31))
        self.LEp.setStyleSheet("QLineEdit{\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgb(0, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"border: none;\n"
"border-bottom: 2px solid rgb(0, 0, 255);\n"
"}")
        self.LEp.setText("")
        self.LEp.setObjectName("LEp")
        self.PBXoakhoa = QtWidgets.QPushButton(self.widget)
        self.PBXoakhoa.setGeometry(QtCore.QRect(299, 100, 101, 41))
        self.PBXoakhoa.setStyleSheet("QPushButton{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 0, 255);\n"
"    border: 3px solid rgb(0, 0, 255);\n"
" }")
        self.PBXoakhoa.setObjectName("PBXoakhoa")
        self.PBTaochuky = QtWidgets.QPushButton(self.widget)
        self.PBTaochuky.setGeometry(QtCore.QRect(780, 330, 151, 41))
        self.PBTaochuky.setStyleSheet("QPushButton{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 0, 255);\n"
"    border: 3px solid rgb(0, 0, 255);\n"
" }")
        self.PBTaochuky.setObjectName("PBTaochuky")
        self.LEMabamSHA1 = QtWidgets.QLineEdit(self.widget)
        self.LEMabamSHA1.setGeometry(QtCore.QRect(520, 390, 531, 61))
        self.LEMabamSHA1.setStyleSheet("QLineEdit{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255,255, 255,50);\n"
"}\n"
"QLineEdit:focus{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}")
        self.LEMabamSHA1.setText("")
        self.LEMabamSHA1.setObjectName("LEMabamSHA1")
        self.LMabamSHA1 = QtWidgets.QLabel(self.widget)
        self.LMabamSHA1.setGeometry(QtCore.QRect(520, 340, 211, 41))
        self.LMabamSHA1.setObjectName("LMabamSHA1")
        self.LEq = QtWidgets.QLineEdit(self.widget)
        self.LEq.setGeometry(QtCore.QRect(60, 270, 131, 31))
        self.LEq.setStyleSheet("QLineEdit{\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgb(0, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"border: none;\n"
"border-bottom: 2px solid rgb(0, 0, 255);\n"
"}")
        self.LEq.setObjectName("LEq")
        self.Ld = QtWidgets.QLabel(self.widget)
        self.Ld.setGeometry(QtCore.QRect(220, 368, 71, 31))
        self.Ld.setObjectName("Ld")
        self.PBTudong = QtWidgets.QPushButton(self.widget)
        self.PBTudong.setGeometry(QtCore.QRect(30, 100, 131, 41))
        self.PBTudong.setStyleSheet("QPushButton{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 0, 255);\n"
"    border: 3px solid rgb(0, 0, 255);\n"
" }")
        self.PBTudong.setObjectName("PBTudong")
        self.PBThoat = QtWidgets.QPushButton(self.widget)
        self.PBThoat.setGeometry(QtCore.QRect(950, 610, 101, 41))
        self.PBThoat.setStyleSheet("QPushButton{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);\n"
"border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: rgb(0, 0, 255);\n"
"    border: 3px solid rgb(0, 0, 255);\n"
" }")
        self.PBThoat.setObjectName("PBThoat")
        self.Lne = QtWidgets.QLabel(self.widget)
        self.Lne.setGeometry(QtCore.QRect(240, 470, 301, 51))
        self.Lne.setStyleSheet("color: rgb(0, 255, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.Lne.setObjectName("Lne")
        self.Lnd = QtWidgets.QLabel(self.widget)
        self.Lnd.setGeometry(QtCore.QRect(200, 570, 261, 51))
        self.Lnd.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.Lnd.setObjectName("Lnd")
        self.LLammo = QtWidgets.QLabel(self.widget)
        self.LLammo.setGeometry(QtCore.QRect(0, 0, 1080, 675))
        self.LLammo.setStyleSheet("QLabel{\n"
"background-color: rgba(0, 0, 0, 150);\n"
"border-radius: 50px;\n"
"}")
        self.LLammo.setText("")
        self.LLammo.setObjectName("LLammo")
        self.LLammo.raise_()
        self.LKhoabimat.raise_()
        self.PBTinh.raise_()
        self.TEThongdiepdulieu.raise_()
        self.LTaochukysoRSA.raise_()
        self.Lp.raise_()
        self.LEPn.raise_()
        self.Lq.raise_()
        self.LThongdiepdulieu.raise_()
        self.Le.raise_()
        self.LPn.raise_()
        self.LEn.raise_()
        self.LEd.raise_()
        self.LKhoacongkhai.raise_()
        self.PBGui.raise_()
        self.PBXoachuky.raise_()
        self.Ln.raise_()
        self.LSinhkhoa.raise_()
        self.LEe.raise_()
        self.TEChukyso.raise_()
        self.LChukyso.raise_()
        self.LEp.raise_()
        self.PBXoakhoa.raise_()
        self.PBTaochuky.raise_()
        self.LEMabamSHA1.raise_()
        self.LMabamSHA1.raise_()
        self.LEq.raise_()
        self.Ld.raise_()
        self.PBTudong.raise_()
        self.PBThoat.raise_()
        self.Lne.raise_()
        self.Lnd.raise_()

        self.retranslateUi(Bengui)
        QtCore.QMetaObject.connectSlotsByName(Bengui)

    def retranslateUi(self, Bengui):
        _translate = QtCore.QCoreApplication.translate
        Bengui.setWindowTitle(_translate("Bengui", "Form"))
        self.LKhoabimat.setText(_translate("Bengui", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic; text-decoration: underline; color:#ff0000;\">Khóa bí mật:</span></p></body></html>"))
        self.PBTinh.setText(_translate("Bengui", "Tính"))
        self.TEThongdiepdulieu.setHtml(_translate("Bengui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt; font-weight:400;\"><br /></p></body></html>"))
        self.LTaochukysoRSA.setText(_translate("Bengui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; font-style:italic; color:#00ff00;\">Tạo chữ ký số RSA</span></p></body></html>"))
        self.Lp.setText(_translate("Bengui", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00ff00;\">p:</span></p></body></html>"))
        self.Lq.setText(_translate("Bengui", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00ff00;\">q:</span></p></body></html>"))
        self.LThongdiepdulieu.setText(_translate("Bengui", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00ff00;\">Thông điệp dữ liệu:</span></p></body></html>"))
        self.Le.setText(_translate("Bengui", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00ff00;\">e:</span></p></body></html>"))
        self.LPn.setText(_translate("Bengui", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#00ff00;\">φ(n):</span></p></body></html>"))
        self.LEn.setWhatsThis(_translate("Bengui", "<html><head/><body><p><span style=\" color:#00ff00;\">sfdf</span></p></body></html>"))
        self.LKhoacongkhai.setText(_translate("Bengui", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00ff00;\">Khóa công khai:</span></p></body></html>"))
        self.PBGui.setText(_translate("Bengui", "Gửi >>>"))
        self.PBXoachuky.setText(_translate("Bengui", "Xóa"))
        self.Ln.setText(_translate("Bengui", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00ff00;\">n:</span></p></body></html>"))
        self.LSinhkhoa.setText(_translate("Bengui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; font-style:italic; color:#00ff00;\">Sinh khóa</span></p></body></html>"))
        self.LChukyso.setText(_translate("Bengui", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00ff00;\">Chữ ký số:</span></p></body></html>"))
        self.PBXoakhoa.setText(_translate("Bengui", "Xóa"))
        self.PBTaochuky.setText(_translate("Bengui", "Tạo chữ ký"))
        self.LMabamSHA1.setText(_translate("Bengui", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00ff00;\">Mã băm (SHA1):</span></p></body></html>"))
        self.Ld.setText(_translate("Bengui", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00ff00;\">d:</span></p></body></html>"))
        self.PBTudong.setText(_translate("Bengui", "Tự động"))
        self.PBThoat.setText(_translate("Bengui", "Thoát"))
        self.Lne.setText(_translate("Bengui", "<html><head/><body><p><br/></p></body></html>"))
        self.Lnd.setText(_translate("Bengui", "<html><head/><body><p><br/></p></body></html>"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bengui = QtWidgets.QWidget()
    ui = Ui_Bengui()
    ui.setupUi(Bengui)
    Bengui.show()
    sys.exit(app.exec_())
